### ISSUE TITLE
Incompatible with latest OutFox LTS

### ISSUE THREAD

**Issue by RuiNtD** [dguzek/Simply-Love-SM5#441]
Simply Love is apparently incompatible with the latest OutFox LTS.
I assume SL just doesn't like the "LTS" in the version name.
![](https://i.imgur.com/0mXTMX1.png)

**Comment by JapanYoshi** [comment]
Having the same error. I think it's a side-effect of the version check breaking, since the version text no longer starts with "SM5.3", but with "OutFox".

**Comment by JustMoneko** [comment]
This issue also applies to Alpha 5 builds of OutFox
![image](https://user-images.githubusercontent.com/63615036/224719917-5bc39e12-a521-42b1-afb8-6441028e08b0.png)

**Comment by beremy-codeboi** [comment]
Oh I had the same problem as y'all. I installed stepmania and the problem went away

**Comment by JapanYoshi** [comment]
> Oh I had the same problem as y'all. I installed stepmania and the problem went away

“Oh, just use a different version of the base game that has fewer features”

It did not make the problem go away. You went away from the problem.

**Comment by beremy-codeboi** [comment]
> > Oh I had the same problem as y'all. I installed stepmania and the problem went away
> 
> “Oh, just use a different version of the base game that has fewer features”
> 
> It did not make the problem go away. You went away from the problem.

Sorry I think I misunderstood. Which game did you install?

**Comment by JapanYoshi** [comment]
It’s in the thread. Can you read?

**Comment by beremy-codeboi** [comment]
OH okay yeah sorry, I get what you're saying now.

I think what's happening is that simply love is checking for the "stepmania" program to be installed. I'm not an expert at code but I think "outfox" is a different program

**Comment by JapanYoshi** [comment]
Project Outfox is a fork of Stepmania 5 which supports all Stepmania 5.0.12 and 5.1 content. You may know it as the version formerly known as Stepmania 5.3.

Because of past frictions towards 5.3, and because your comment was sarcastic and unhelpful to solve the issue at hand, I was assuming that you were passive-aggressively trying to get us to stop using 5.3 and start using 5.0 or 5.1 instead.

**Comment by beremy-codeboi** [comment]
> Project Outfox is a fork of Stepmania 5 which supports all Stepmania 5.0.12 and 5.1 content.

Based on this issue existing, I think that's a little bit of false advertisement

**Comment by JapanYoshi** [comment]
>Based on this issue existing, I think that's a little bit of false advertisement

If Simply Love didn’t **block any version except for SM5.0.12 or SM5.1**, it would work perfectly. We’ve been over this before, and the issue is supposed to have been resolved. Simply Love used to have **lockout code** for 5.3.

Project Outfox supports all 5.0.12 or 5.1 content, and that’s a fact. It’s also a fact that Simply Love refuses to support Project Outfox, despite it working perfectly.

**Comment by RuiNtD** [comment]
> It’s also a fact that Simply Love refuses to support Project Outfox, despite it working perfectly.

![](https://i.imgur.com/l11eh9k.png)

Also, the incompatibility was fixed in the latest release. lol

**Comment by JapanYoshi** [comment]
> Also, the incompatibility was fixed in the latest release. lol

False. SL rejects Outfox 0.4.18.1.

![image](https://user-images.githubusercontent.com/8707990/226161452-659838dc-aca2-46ee-badf-6db0aa04c9a6.png)

**Comment by RuiNtD** [comment]
Oh, whoops. I tested it in OutFox 5.0 (from Steam). Still broken on OutFox LTS.

**Comment by JapanYoshi** [comment]
Why bother having lockout code for this? Just display a banner in the home screen that says “You are running [version] while we only support SM5.0.12, 5.1, and OutFox. Do not report bugs unless they can also be reproduced on one of them.”
